/-
  Enfflash formalization — the clauses generated by the compiler are well
  formed.

  The enforcement rewriting (`Rw`) and the gating of realizations only
  produce clauses whose effect terms are well-formed, whose local variables
  read by the effect are bound by every guard (the paper's syntactic
  requirement on EF clauses, Section 3.1), whose let atoms in guards are
  enumerable, and whose deferred effects are at least one step ahead
  (`GoodClause`, `Rw.good`, `gate_good`).  Together with `exists_known`
  (the constants and context values of finitely many rules form a finite
  set), this discharges the side conditions of the data-flow analysis
  (`DFClause`) and the bounds on deferred effects: the only checks left are
  the two checks of the paper (Section 4.5).
-/
import Enfflash.TypeSystem

namespace Enfflash

/-! ## Well-formed let bodies -/

section
variable {B D : Type}

/-- Well-formed let bodies: their formulas and terms are well-formed. -/
def LBody.WF {L : Type} : LBody B L D → Prop
  | .now φ | .prev _ _ φ => φ.WF
  | .since _ _ φl φr => φl.WF ∧ φr.WF
  | .agg _ _ ts _ φ => φ.WF ∧ ∀ t ∈ ts, t.WF

theorem upSn_WF {s : ℕ → Term D} (hs : ∀ n, (s n).WF) : ∀ k n, (upSn k s n).WF
  | 0, n => hs n
  | k + 1, n => upS_WF (upSn_WF hs k) n

theorem ren_WF (xs : List ℕ) : ∀ n, (ren xs n : Term D).WF := fun _ => trivial

theorem letsWF_snoc {Γ : List (LetDef B ℕ D)} (h : ∀ (p : ℕ) (d : LetDef B ℕ D), Γ[p]? = some d → d.body.WF)
    {d : LetDef B ℕ D} (hd : d.body.WF) :
    ∀ (p : ℕ) (d' : LetDef B ℕ D), (Γ ++ [d])[p]? = some d' → d'.body.WF := by
  intro p d' hp
  rcases getElem?_append_last hp with ⟨-, hp⟩ | ⟨rfl, rfl⟩
  exacts [h p d' hp, hd]

/-- Let-normalization only creates well-formed let bodies. -/
theorem norm_letsWF (φ : MF B D) : ∀ ars, φ.WF ars → ∀ U (Γ : List (LetDef B ℕ D)),
    (∀ (p : ℕ) (d : LetDef B ℕ D), Γ[p]? = some d → d.body.WF) →
    ∀ (p : ℕ) (d : LetDef B ℕ D), (norm φ U Γ).2[p]? = some d → d.body.WF := by
  induction φ with
  | tt | eq | pred | upred => intro ars _ U Γ hΓ; exact hΓ
  | neg φ ih | nx _ _ φ ih | ev _ _ φ ih => intro ars hφ U Γ hΓ; exact ih ars hφ U Γ hΓ
  | conj φ ψ ih₁ ih₂ => intro ars hφ U Γ hΓ; exact ih₂ ars hφ.2 U _ (ih₁ ars hφ.1 U Γ hΓ)
  | ex φ ih =>
    intro ars hφ U Γ hΓ
    have h1 := ih ars hφ U Γ hΓ
    simp only [norm]
    split
    · exact letsWF_snoc h1 (Fm.WF_subst (norm_correct φ ars hφ U Γ).1 (upS_WF (ren_WF _)))
    · exact h1
  | prev a b φ ih =>
    intro ars hφ U Γ hΓ
    exact letsWF_snoc (ih ars hφ U Γ hΓ)
      (Fm.WF_subst (norm_correct φ ars hφ U Γ).1 (ren_WF _))
  | since a b φ ψ ih₁ ih₂ =>
    intro ars hφ U Γ hΓ
    exact letsWF_snoc (ih₂ ars hφ.2 U _ (ih₁ ars hφ.1 U Γ hΓ))
      ⟨Fm.WF_subst (norm_correct φ ars hφ.1 U Γ).1 (ren_WF _),
        Fm.WF_subst (norm_correct ψ ars hφ.2 U _).1 (ren_WF _)⟩
  | letin ar body rest ih₁ ih₂ =>
    intro ars hφ U Γ hΓ
    exact ih₂ (ar :: ars) hφ.2.2 _ _
      (letsWF_snoc (ih₁ ars hφ.1 U Γ hΓ) (norm_correct body ars hφ.1 U Γ).1)
  | agg k ω ts ys φ ih =>
    intro ars hφ U Γ hΓ
    refine letsWF_snoc (ih ars hφ.1 U Γ hΓ)
      ⟨Fm.WF_subst (norm_correct φ ars hφ.1 U Γ).1 (upSn_WF (ren_WF _) k), fun t ht => ?_⟩
    obtain ⟨t₀, ht₀, rfl⟩ := List.mem_map.1 ht
    exact Term.WF_subst (hφ.2 t₀ ht₀) (upSn_WF (ren_WF _) k)

/-- The lets of the let-normal form of a well-formed formula are well-formed. -/
theorem lnf_letsWF (φ : MF B D) (hφ : φ.WF []) :
    ∀ (p : ℕ) (d : LetDef B ℕ D), (lnf φ).2[p]? = some d → d.body.WF :=
  norm_letsWF φ [] hφ [] [] (by intro p d h; simp at h)

theorem cauTarget_WF {L : Type} {body : LBody B L D} {ψ : Fm B L D} (hb : body.WF)
    (h : body.cauTarget = some ψ) : ψ.WF := by
  cases body with
  | now φ => cases h; exact hb
  | since a b φl φr =>
    simp only [LBody.cauTarget] at h
    split at h
    · cases h; exact hb.2
    · cases h
  | prev => cases h
  | agg => cases h

theorem supTarget_WF {L : Type} {body : LBody B L D} {ψ : Fm B L D} (hb : body.WF)
    (h : body.supTarget = some ψ) : ψ.WF := by
  cases body with
  | now φ => cases h; exact hb
  | since a b φl φr =>
    simp only [LBody.supTarget] at h
    split at h
    · cases h; exact ⟨hb.1, hb.2⟩
    · cases h; exact hb.1
  | prev => cases h
  | agg => cases h

end

/-! ## Well-formed clauses -/

section
variable {B L D : Type}

/-- A well-formed generated clause (w.r.t. the enumerable predicates `m`):
    well-formed effect terms, local variables read by the effect bound by
    every guard, enumerable let atoms in guards, and deferred effects at
    least one step ahead. -/
structure GoodClause (m : Pr B L → Prop) (c : Clause B L D) : Prop where
  wf : ∀ t ∈ c.eff.args, t.WF
  locals : ∀ t ∈ c.eff.args, ∀ x ∈ t.supp, x < c.nloc → c.trig.guards.bindsAll x
  lets : ∀ κ ∈ c.trig.guards, ∀ a ∈ κ, ∀ q ts, a = .pred (.lp q) ts → m (.lp q)
  later : ∀ b e ts, c.eff = .later b e ts → 1 ≤ b
  next : ∀ n t e ts, c.eff = .next n t e ts → 1 ≤ n ∧ (t = true → n = 1)

/-- A clause with no local variables, trivial guards, and an immediate
    effect on well-formed terms. -/
theorem good_simple {m : Pr B L → Prop} {c : Clause B L D} (hn : c.nloc = 0)
    (hg : c.trig.guards = [[]]) (hwf : ∀ t ∈ c.eff.args, t.WF)
    (hl : ∀ b e ts, c.eff ≠ .later b e ts) (hx : ∀ n t e ts, c.eff ≠ .next n t e ts) :
    GoodClause m c where
  wf := hwf
  locals := fun _ _ x _ h => (Nat.not_lt_zero x (hn ▸ h)).elim
  lets := by rw [hg]; intro κ hκ a ha; simp at hκ; subst hκ; simp at ha
  later := fun b e ts h => absurd h (hl b e ts)
  next := fun n t e ts h => absurd h (hx n t e ts)

theorem good_addFilter {m : Pr B L → Prop} {c : Clause B L D} (h : GoodClause m c)
    (ψ : Fm B L D) : GoodClause m (c.addFilter ψ) :=
  ⟨h.wf, h.locals, h.lets, h.later, h.next⟩

theorem supp_liftS (k : ℕ) (t : Term D) : ∀ x ∈ (t.subst (liftS k)).supp, k ≤ x := by
  intro x hx
  cases t with
  | var n => simp [Term.subst, liftS, Term.supp] at hx; omega
  | const => simp [Term.subst, Term.supp] at hx
  | fn f xs =>
    simp only [Term.subst, Term.supp, List.mem_flatMap] at hx
    obtain ⟨n, -, hx⟩ := hx
    simp [liftS] at hx; omega

/-- Under a substitution keeping the first `k` variables and mapping the
    others to terms over variables `≥ k`, a local variable of the result
    comes from the same variable. -/
theorem supp_subst_local {k : ℕ} {s : ℕ → Term D} (h1 : ∀ n < k, s n = .var n)
    (h2 : ∀ n, k ≤ n → ∀ x ∈ (s n).supp, k ≤ x) (t : Term D) {x : ℕ}
    (hx : x ∈ (t.subst s).supp) (hxk : x < k) : x ∈ t.supp := by
  have hvar : ∀ n, x ∈ (s n).supp → x = n := by
    intro n hn
    by_cases hnk : n < k
    · rw [h1 n hnk] at hn; simpa [Term.supp] using hn
    · exact absurd (h2 n (by omega) x hn) (by omega)
  cases t with
  | var n => simp only [Term.subst, Term.supp] at hx ⊢; simp [hvar n hx]
  | const => simp [Term.subst, Term.supp] at hx
  | fn f xs =>
    simp only [Term.subst, Term.supp, List.mem_flatMap] at hx
    obtain ⟨n, hn, hx⟩ := hx
    rw [hvar n hx]; exact hn

theorem good_substCtx {m : Pr B L → Prop} {c : Clause B L D} (h : GoodClause m c)
    {s : ℕ → Term D} (hs : ∀ n, (s n).WF) : GoodClause m (c.substCtx s) := by
  set s' : ℕ → Term D := fun n =>
    if n < c.nloc then .var n else (s (n - c.nloc)).subst (liftS c.nloc) with hs'
  have hs'wf : ∀ n, (s' n).WF := by
    intro n; simp only [hs']; split
    · trivial
    · exact Term.WF_subst (hs _) fun _ => trivial
  have h1 : ∀ n < c.nloc, s' n = .var n := fun n hn => by simp [hs', hn]
  have h2 : ∀ n, c.nloc ≤ n → ∀ x ∈ (s' n).supp, c.nloc ≤ x := by
    intro n hn x hx
    simp only [hs', show ¬ n < c.nloc by omega, if_false] at hx
    exact supp_liftS _ _ x hx
  have hargs : (c.substCtx s).eff.args = c.eff.args.map (Term.subst s') := by
    simp only [Clause.substCtx]; cases c.eff <;> rfl
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · rw [hargs]; intro t ht
    obtain ⟨t₀, ht₀, rfl⟩ := List.mem_map.1 ht
    exact Term.WF_subst (h.wf t₀ ht₀) hs'wf
  · rw [hargs]; intro t ht x hx hxl
    obtain ⟨t₀, ht₀, rfl⟩ := List.mem_map.1 ht
    have hxt := supp_subst_local h1 h2 t₀ hx hxl
    have ht := ht₀
    intro κ hκ
    simp only [Clause.substCtx, Trigger.subst, Guards.subst, List.mem_map] at hκ
    obtain ⟨κ₀, hκ₀, rfl⟩ := hκ
    obtain ⟨a, ha, hb⟩ := h.locals t₀ ht x hxt hxl κ₀ hκ₀
    refine ⟨a.subst s', List.mem_map_of_mem ha, ?_⟩
    rcases a with ⟨p, ts⟩ | ⟨t', d⟩
    · simp only [GAtom.binds, GAtom.subst] at hb ⊢
      exact List.mem_map.2 ⟨_, hb, by simp [Term.subst, h1 x hxl]⟩
    · simp only [GAtom.binds, GAtom.subst] at hb ⊢
      subst hb; simp [Term.subst, h1 x hxl]
  · intro κ hκ a ha q ts he
    simp only [Clause.substCtx, Trigger.subst, Guards.subst, List.mem_map] at hκ
    obtain ⟨κ₀, hκ₀, rfl⟩ := hκ
    obtain ⟨a₀, ha₀, rfl⟩ := List.mem_map.1 ha
    rcases a₀ with ⟨p, ts₀⟩ | ⟨t', d⟩
    · simp only [GAtom.subst, GAtom.pred.injEq] at he
      obtain ⟨rfl, -⟩ := he
      exact h.lets κ₀ hκ₀ _ ha₀ q ts₀ rfl
    · simp [GAtom.subst] at he
  · intro b e ts he
    simp only [Clause.substCtx] at he
    cases hc : c.eff <;> rw [hc] at he <;> simp only [Effect.subst, reduceCtorEq] at he
    obtain ⟨rfl, -, -⟩ := Effect.later.inj he
    exact h.later _ _ _ hc
  · intro n t e ts he
    simp only [Clause.substCtx] at he
    cases hc : c.eff <;> rw [hc] at he <;> simp only [Effect.subst, reduceCtorEq] at he
    obtain ⟨rfl, rfl, -, -⟩ := Effect.next.inj he
    exact h.next _ _ _ _ hc

theorem forall₂_mem_right {α β : Type} {R : α → β → Prop} :
    ∀ {l₁ : List α} {l₂ : List β}, List.Forall₂ R l₁ l₂ → ∀ b ∈ l₂, ∃ a ∈ l₁, R a b
  | _, _, .nil, _, hb => absurd hb (List.not_mem_nil)
  | a :: _, _ :: _, .cons hab hrest, b, hb => by
    rcases List.mem_cons.1 hb with rfl | hb
    · exact ⟨a, List.mem_cons_self .., hab⟩
    · obtain ⟨a', ha', h'⟩ := forall₂_mem_right hrest b hb
      exact ⟨a', List.mem_cons_of_mem _ ha', h'⟩

theorem good_exGuard {m : Pr B L → Prop} {c c' : Clause B L D} (h : GoodClause m c)
    (hg : ExGuard m c c') : GoodClause m c' := by
  obtain ⟨hn, he, hgx⟩ := hg
  refine ⟨he ▸ h.wf, ?_, ?_, he ▸ h.later, he ▸ h.next⟩
  · intro t ht x hx hxl
    rw [he] at ht
    rcases Nat.lt_or_ge x c.nloc with hlt | hge
    · exact hgx.bindsAll_preserved (h.locals t ht x hx hlt)
    · obtain rfl : x = c.nloc := by omega
      exact hgx.sound.2
  · intro κ hκ a ha q ts hq
    exact ((hgx.letInv (S := Set.univ) (fun κ hκ a ha q ts hq => ⟨h.lets κ hκ a ha q ts hq,
      trivial⟩) (fun _ _ => trivial)).1 κ hκ a ha q ts hq).1

theorem simple_mapCau {c : Clause B L D} (hs : c.simple) (f : Ev B L → List (Term D) → Effect B L D) :
    ∃ e ts, c.eff = .cau e ts ∧ Clause.mapCau f c = ⟨0, Trigger.top, f e ts⟩ := by
  obtain ⟨hn, ht, e, ts, he⟩ := hs
  refine ⟨e, ts, he, ?_⟩
  simp only [Clause.mapCau, he, hn, ht]

theorem nxU_WF {φ : Fm B L D} : ∀ n, (nxU n φ).WF → φ.WF
  | 0, h => h
  | n + 1, h => nxU_WF n h

/-- **The rewriting generates well-formed clauses.** -/
theorem Rw.good {S : Sig B L D} (hok : ∀ q, S.okS q → S.enum (.lp q)) {α : Bool}
    {φ : Fm B L D} {CS : List (List (Clause B L D))} (h : Rw S α φ CS) :
    φ.WF → ∀ C ∈ CS, ∀ c ∈ C, GoodClause S.enum c := by
  induction h with
  | tt => intro _ C hC c hc; simp at hC; subst hC; simp at hc
  | evC _ | letC _ _ =>
    intro hφ C hC c hc
    simp at hC; subst hC; simp at hc; subst hc
    exact good_simple rfl rfl hφ (by intros; simp) (by intros; simp)
  | @evS e ts _ =>
    intro hφ C hC c hc
    simp at hC; subst hC; simp at hc; subst hc
    refine ⟨hφ, fun _ _ x _ h => (Nat.not_lt_zero x h).elim, ?_, by intros; simp_all, by intros; simp_all⟩
    intro κ hκ a ha q ts' he
    simp at hκ; subst hκ; simp at ha; subst ha; cases he
  | @letS p ts hp _ =>
    intro hφ C hC c hc
    simp at hC; subst hC; simp at hc; subst hc
    refine ⟨hφ, fun _ _ x _ h => (Nat.not_lt_zero x h).elim, ?_, by intros; simp_all, by intros; simp_all⟩
    intro κ hκ a ha q ts' he
    simp at hκ; subst hκ; simp at ha; subst ha; cases he; exact hok p hp
  | neg _ ih => exact ih
  | andC _ _ ih₁ ih₂ =>
    intro hφ C hC c hc
    simp only [prodCS, List.mem_flatMap, List.mem_map] at hC
    obtain ⟨C₁, h₁, C₂, h₂, rfl⟩ := hC
    rcases List.mem_append.1 hc with hc | hc
    exacts [ih₁ hφ.1 C₁ h₁ c hc, ih₂ hφ.2 C₂ h₂ c hc]
  | andSL _ _ ih =>
    intro hφ C hC c hc
    obtain ⟨C₀, h₀, rfl⟩ := List.mem_map.1 hC
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    exact good_addFilter (ih hφ.1 C₀ h₀ c₀ hc₀) _
  | andSR _ _ ih =>
    intro hφ C hC c hc
    obtain ⟨C₀, h₀, rfl⟩ := List.mem_map.1 hC
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    exact good_addFilter (ih hφ.2 C₀ h₀ c₀ hc₀) _
  | exC _ ih =>
    intro hφ C hC c hc
    obtain ⟨C₀, h₀, rfl⟩ := List.mem_map.1 hC
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    refine good_substCtx (ih hφ C₀ h₀ c₀ hc₀) fun n => ?_
    simp only [instS]; split_ifs <;> trivial
  | exS _ hCS ih =>
    intro hφ C' hC' c hc
    obtain ⟨C, hC, hfa⟩ := hCS C' hC'
    obtain ⟨c₀, hc₀, hg⟩ := forall₂_mem_right hfa c hc
    exact good_exGuard (ih hφ C hC c₀ hc₀) hg
  | futEv _ _ hb hCS ih =>
    intro hφ C' hC' c hc
    obtain ⟨C, hC, -, hs, rfl⟩ := hCS C' hC'
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    obtain ⟨e, ts, he, hm⟩ := simple_mapCau (hs c₀ hc₀) (.later _)
    have hwf := (ih hφ C hC c₀ hc₀).wf
    rw [he] at hwf
    rw [hm]
    refine ⟨hwf, fun _ _ x _ h => (Nat.not_lt_zero x h).elim, ?_, ?_, by intros; simp_all⟩
    · intro κ hκ; simp [Trigger.top, Guards.top] at hκ; subst hκ; simp
    · intro b' e' ts' h; cases h; exact hb
  | futNx1 _ _ hCS ih =>
    intro hφ C' hC' c hc
    obtain ⟨C, hC, -, hs, rfl⟩ := hCS C' hC'
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    obtain ⟨e, ts, he, hm⟩ := simple_mapCau (hs c₀ hc₀) (.next 1 true)
    have hwf := (ih hφ C hC c₀ hc₀).wf
    rw [he] at hwf
    rw [hm]
    refine ⟨hwf, fun _ _ x _ h => (Nat.not_lt_zero x h).elim, ?_, by intros; simp_all, ?_⟩
    · intro κ hκ; simp [Trigger.top, Guards.top] at hκ; subst hκ; simp
    · intro n t e' ts' h; cases h; exact ⟨le_rfl, fun _ => rfl⟩
  | futNxU _ hn hCS ih =>
    intro hφ C' hC' c hc
    obtain ⟨C, hC, hs, rfl⟩ := hCS C' hC'
    obtain ⟨c₀, hc₀, rfl⟩ := List.mem_map.1 hc
    obtain ⟨e, ts, he, hm⟩ := simple_mapCau (hs c₀ hc₀) (.next _ false)
    have hwf := (ih (nxU_WF _ hφ) C hC c₀ hc₀).wf
    rw [he] at hwf
    rw [hm]
    refine ⟨hwf, fun _ _ x _ h => (Nat.not_lt_zero x h).elim, ?_, by intros; simp_all, ?_⟩
    · intro κ hκ; simp [Trigger.top, Guards.top] at hκ; subst hκ; simp
    · intro n t e' ts' h; cases h; exact ⟨hn, fun h => absurd h (by simp)⟩

/-- Gating keeps clauses well-formed. -/
theorem gate_good {m : Pr B L → Prop} {c : Clause B L D} (h : GoodClause m c) (o : Ev B L)
    (k : ℕ) : GoodClause m (gate o k c) := by
  refine ⟨h.wf, ?_, ?_, h.later, h.next⟩
  · intro t ht x hx hxl κ hκ
    simp only [gate, Guards.addAtom, List.mem_map] at hκ
    obtain ⟨κ₀, hκ₀, rfl⟩ := hκ
    rcases Nat.lt_or_ge x c.nloc with hlt | hge
    · obtain ⟨a, ha, hb⟩ := h.locals t ht x hx hlt κ₀ hκ₀
      exact ⟨a, List.mem_append_left _ ha, hb⟩
    · refine ⟨_, List.mem_append_right _ (List.mem_singleton_self _), ?_⟩
      simp only [GAtom.binds, argVars, List.mem_map, List.mem_range]
      exact ⟨x - c.nloc, by simp only [gate] at hxl; omega, by congr 1; omega⟩
  · intro κ hκ a ha q ts he
    simp only [gate, Guards.addAtom, List.mem_map] at hκ
    obtain ⟨κ₀, hκ₀, rfl⟩ := hκ
    rcases List.mem_append.1 ha with ha | ha
    · exact h.lets κ₀ hκ₀ a ha q ts he
    · simp at ha; subst ha; cases he

/-! ## Known values of finitely many rules -/

/-- The constants and context values used by finitely many rules form a
    finite set. -/
theorem exists_known (rules : List (Clause B L D)) (v₀ : ℕ → D) :
    ∃ V : Set D, V.Finite ∧ ∀ c ∈ rules,
      (∀ t ∈ c.eff.args, ∀ d, t = .const d → d ∈ V) ∧
      (∀ t ∈ c.eff.args, ∀ x ∈ t.supp, c.nloc ≤ x → v₀ (x - c.nloc) ∈ V) ∧
      (∀ κ ∈ c.trig.guards, ∀ a ∈ κ, ∀ t d, a = .eq t d → d ∈ V) := by
  let f : Clause B L D → List D := fun c =>
    c.eff.args.filterMap (fun t => match t with | .const d => some d | _ => none) ++
    c.eff.args.flatMap (fun t => t.supp.map fun x => v₀ (x - c.nloc)) ++
    c.trig.guards.flatten.filterMap (fun a => match a with | .eq _ d => some d | _ => none)
  refine ⟨{d | d ∈ rules.flatMap f}, List.finite_toSet _, fun c hc => ⟨?_, ?_, ?_⟩⟩
  · intro t ht d htd
    exact List.mem_flatMap.2 ⟨c, hc, List.mem_append_left _ (List.mem_append_left _
      (List.mem_filterMap.2 ⟨t, ht, by subst htd; rfl⟩))⟩
  · intro t ht x hx _
    exact List.mem_flatMap.2 ⟨c, hc, List.mem_append_left _ (List.mem_append_right _
      (List.mem_flatMap.2 ⟨t, ht, List.mem_map_of_mem hx⟩))⟩
  · intro κ hκ a ha t d had
    exact List.mem_flatMap.2 ⟨c, hc, List.mem_append_right _
      (List.mem_filterMap.2 ⟨a, List.mem_flatten.2 ⟨κ, hκ, ha⟩, by subst had; rfl⟩)⟩

/-- **The data-flow side conditions hold for well-formed clauses.** -/
theorem dfClause_of_good (rules : List (Clause B L D)) (v₀ : ℕ → D) {m : Pr B L → Prop}
    (ok : L → Prop) (hm : ∀ q, m (.lp q) → ok q) (hgood : ∀ c ∈ rules, GoodClause m c) :
    ∃ V : Set D, V.Finite ∧ ∀ c ∈ rules, DFClause V v₀ ok c := by
  obtain ⟨V, hV, hk⟩ := exists_known rules v₀
  refine ⟨V, hV, fun c hc => ?_⟩
  obtain ⟨h1, h2, h3⟩ := hk c hc
  have hg := hgood c hc
  exact ⟨hg.wf, h1, hg.locals, h2, h3, fun κ hκ a ha q ts he => hm q (hg.lets κ hκ a ha q ts he)⟩

end

end Enfflash
