/-
  Enfflash formalization — end-to-end correctness.

  From an MFOTL policy `□φ`:
  1. let-normalization produces lets `Γ` and a formula `χ` (`LetNormal`);
  2. the compiler produces clauses for `χ` and realizations for the lets,
     sectioned along the SCCs of the EDG (with lets decomposed by `ldOf`) and
     checked for conflicts (`Rewrite`, `Realize`, `EDG`, `Conflict`);
  3. the enforcement loop runs the program with concrete tables (`Loop`,
     `TableImpl`) and a terminating `Saturate` (`DFG`, `TableDeps`).

  `enforcement_correct`: for a `Policy` `Φ`, a `Compiled` program `P` whose
  `Checks` succeed, `enforce P` is a `SoundEnforcer` of `□φ`: on every valid
  `InputTrace`, every output of the loop satisfies `□φ`.  Finite
  input traces are covered by causality (`LoopParams.pt_congr`,
  `LoopParams.before_react`): the output up to the last input is the same for
  every extension of the input.
-/
import Enfflash.Conflict
import Enfflash.Clauses

namespace Enfflash

variable {B D : Type}

open LoopParams

theorem pt_K {Q : LoopParams B ℕ D} {v₀ : ℕ → D} (hQ : Q.Wf v₀) (j : ℕ) :
    ∃ tab t, (pt hQ j).K = Q.ctx tab t :=
  ⟨_, _, (pt_spec hQ j).2.K⟩

/-- The lets of the let-normal form are ordered. -/
theorem lnf_ordered (φ : MF B D) (hφ : φ.WF []) : LetsOrdered (norm φ [] []).2 :=
  (norm_ordered φ [] hφ [] [] rfl (by simp) (by intro p d h; simp at h)).1

/-! ## Input traces -/

/-- A valid input trace: monotone, progressing timestamps and finite
    databases. -/
structure InputTrace (B D : Type) where
  τ : ℕ → ℕ
  db : ℕ → DB B ℕ D
  mono : Monotone τ
  progress : ∀ t, ∃ k, t < τ k
  finite : ∀ k, (db k).Finite

/-! ## Policies -/

/-- A policy `□φ`: a well-formed MFOTL formula whose past operators and let
    bodies are future-free. -/
structure Policy (B D : Type) where
  φ : MF B D
  wf : φ.WF []
  past : φ.PastPure

namespace Policy

variable (Φ : Policy B D)

/-- The let bindings `Γ` of the let-normal form of `φ`. -/
abbrev Γ : List (LetDef B ℕ D) := (lnf Φ.φ).2

/-- The formula `χ` of the let-normal form of `φ`. -/
abbrev χ : Fm B ℕ D := (lnf Φ.φ).1

end Policy

/-! ## Compiled programs -/

/-- The output of the compiler for a policy `Φ` (paper, Algorithm 4,
    `P = Compile(Γ, R, ≺)`): a successful `Compilation` (guards for the lets,
    a valid realization, and a candidate clause set `C` for `χ`), the rules of
    the program (exactly `C` and the realization clauses, all with present
    filters), and their sections along a topological order `≺` of the SCCs of
    the EDG.  `v₀` is the default valuation. -/
structure Compiled (Φ : Policy B D) where
  S₀ : Sig B ℕ D
  C : List (Clause B ℕ D)
  comp : Compilation S₀ Φ.φ C
  rules : List (Clause B ℕ D)
  v₀ : ℕ → D
  hasC : ∀ c ∈ C, c ∈ rules
  hasR : ∀ c, comp.R.clauses S₀.ar c → c ∈ rules
  only : ∀ c ∈ rules, c ∈ C ∨ comp.R.clauses S₀.ar c
  present : ∀ c ∈ rules, c.trig.filter.present
  secs : List (List (Clause B ℕ D))
  order : SCCOrder (ldOf Φ.Γ) rules secs

namespace Compiled

variable {Φ : Policy B D} (P : Compiled Φ)

/-- The guards of the lets. -/
abbrev gd : ℕ → Option (Guards B ℕ D) := P.comp.gd

/-- The EF program: one section per SCC of the EDG, in the order `≺`. -/
def prog : Program B ℕ D := ⟨P.secs⟩

theorem mem_prog (c : Clause B ℕ D) : c ∈ P.prog.rules ↔ c ∈ P.rules :=
  P.order.cover c

/-- **The rules of a compiled program are well-formed** (`GoodClause`): they
    are generated by the rewriting, possibly gated by an obligation event. -/
theorem good : ∀ c ∈ P.rules, GoodClause (enumOf P.gd) c := by
  have hok : ∀ ok : ℕ → Prop, ∀ q,
      (P.comp.R.scope (sigOf P.S₀ (enumOf P.gd) (fun _ => False) (fun _ => False)) ok).okS q →
      enumOf P.gd (.lp q) := fun ok q h => P.comp.supGuarded q h.2
  have hlets := lnf_letsWF Φ.φ Φ.wf
  intro c hc
  rcases P.only c hc with hC | hR
  · exact Rw.good (hok _) P.comp.rewrite (norm_correct Φ.φ [] Φ.wf [] []).1 _ P.comp.choice c hC
  · rcases hR with ⟨p, C, hCp, c₀, hc₀, rfl⟩ | ⟨p, C, hCp, c₀, hc₀, rfl⟩
    · obtain ⟨d, φ, CS, hd, -, ht, hrw, hCS⟩ := P.comp.valid.cau p C hCp
      exact gate_good (Rw.good (hok _) hrw (cauTarget_WF (hlets p d hd) ht) C hCS c₀ hc₀) _ _
    · obtain ⟨d, φ, CS, hd, -, ht, hrw, hCS⟩ := P.comp.valid.sup p C hCp
      exact gate_good (Rw.good (hok _) hrw (supTarget_WF (hlets p d hd) ht) C hCS c₀ hc₀) _ _

/-- The two checks of the compiler (paper, Section 4.5): the cause/suppress
    conflict check (`conflicts`, for every rule of a section against every
    rule, in the let interpretation of any time-point) and the data-flow
    check (`acyclic`: no non-stable edge on a cycle, for the stability closure
    `Stab` of the stable functions). -/
structure Checks : Prop where
  conflicts : ∀ tab t, ∀ sec ∈ P.prog.secs, ∀ c₁ ∈ sec, ∀ c₂ ∈ P.rules,
    Exclusive (⟨fun W => lvOf Φ.Γ P.v₀ tab t W, P.v₀⟩ : Ctx B ℕ D) (effNames sec)ᶜ c₁ c₂
  acyclic : ∃ Stab : Set D → Set D, StabOp Stab ∧
    ∀ sec ∈ P.prog.secs, DFGAcyclic (lsrcOf Φ.Γ P.gd) (nsrcOf Φ.Γ P.gd) Stab sec

variable {P}

/-- The loop parameters for running `P` on `ρ` with concrete tables. -/
noncomputable abbrev params (P : Compiled Φ) (ρ : InputTrace B D) : LoopParams B ℕ D :=
  tableParams Φ.Γ P.v₀ ρ.τ ρ.db P.prog (satFn P.prog.secs)

theorem Checks.wf (h : P.Checks) (ρ : InputTrace B D) : (params P ρ).Wf P.v₀ := by
  obtain ⟨Vr, hVr, hdf⟩ := dfClause_of_good P.rules P.v₀ (fun q => (P.gd q).isSome)
    (fun q h => h) P.good
  obtain ⟨Stab, hS, hacyc⟩ := h.acyclic
  exact tableParams_wf Φ.Γ P.v₀ ρ.τ ρ.db P.prog ρ.mono ρ.progress ρ.finite
    (lnf_ordered Φ.φ Φ.wf) P.gd P.comp.guards Vr hVr
    (fun sec hs c hc => hdf c ((P.mem_prog c).1 (List.mem_flatten.2 ⟨sec, hs, hc⟩)))
    hS hacyc (fun c hc => (P.good c ((P.mem_prog c).1 hc)).later)
    (fun c hc => (P.good c ((P.mem_prog c).1 hc)).next)

end Compiled

/-! ## Compilation correctness for a run of the loop

The clauses hold at every time-point of any run of the enforcement loop whose
sections follow a topological SCC order and pass the conflict check; the
end-to-end theorem below instantiates the run with the loop program. -/

section
variable {L : Type}

/-- **Compilation correctness** for a run of the enforcement loop with
    `P = Compile(Γ, R, ≺)` (Algorithm 4).  Let `□χ` be in let-normal form,
    `R` a valid realization of its lets, `C` a candidate clause set for `χ`,
    and the rules (containing `C` and the gated realization clauses, with
    present filters) sectioned along a topological order `≺` of the SCCs of
    the EDG (`SCCOrder`).  If the conflict check passes, every output of a
    run of the loop whose tables compute the lets satisfies `□χ`. -/
theorem enforcer_sound_topo {S : Sig B L D} {Γ : L → Option (LetDef B L D)}
    {R : Real B L D} {r : L → L → Prop} (hwf : WellFounded r) (hV : R.Valid S Γ r)
    {χ : Fm B L D} {CS : List (List (Clause B L D))}
    (hrw : Rw (R.scope S (fun _ => True)) true χ CS) {C : List (Clause B L D)} (hC : C ∈ CS)
    (ld : L → List (Ev B L)) (rules : List (Clause B L D))
    (hPC : ∀ c ∈ C, c ∈ rules) (hPR : ∀ c, R.clauses S.ar c → c ∈ rules)
    (hpres : ∀ c ∈ rules, c.trig.filter.present)
    {secs : List (List (Clause B L D))} (hord : SCCOrder ld rules secs)
    {σ : Tr B L D} {v₀ : ℕ → D} (run : LoopRun ⟨secs⟩ σ v₀)
    (hm : Monotone σ.ts) (htab : TablesComputeLets σ v₀ Γ)
    (hld : ∀ j, LetDeps (run.K j) ld)
    (hchk : ∀ j, ∀ sec ∈ secs, ∀ c₁ ∈ sec, ∀ c₂ ∈ rules,
      Exclusive (run.K j) (effNames sec)ᶜ c₁ c₂) :
    ∀ i, σ.sat i v₀ χ := by
  have hmem : ∀ c, c ∈ (⟨secs⟩ : Program B L D).rules ↔ c ∈ rules := hord.cover
  obtain ⟨hnow, hdef⟩ := Exclusive.split (K := run.K) (secs := secs)
    fun j sec hs c₁ h₁ c₂ h₂ => hchk j sec hs c₁ h₁ c₂ ((hmem c₂).1 h₂)
  exact enforcer_sound hwf hV hrw hC ⟨secs⟩
    (fun c hc => (hmem c).2 (hPC c hc)) (fun c hc => (hmem c).2 (hPR c hc))
    (fun c hc => hpres c ((hmem c).1 hc)) run hm
    (fun j => stratified_of_topo (hld j) rules secs
      (fun sec hs c hc => (hmem c).1 (List.mem_flatten.2 ⟨sec, hs, hc⟩)) hord.topo)
    (run.conflictFree hord.topo.sectionsDisjoint hnow hdef)
    (letSem_of_tables σ v₀ htab)

end

/-! ## The enforcer -/

/-- The enforcer: the output trace of the enforcement loop running the
    compiled program `P` on the input trace `ρ`. -/
noncomputable def enforce {Φ : Policy B D} (P : Compiled Φ) (h : P.Checks)
    (ρ : InputTrace B D) : Tr B ℕ D :=
  outTr (h.wf ρ)

/-- A function from input to output traces is a sound enforcer of `□φ` if
    all its outputs satisfy `□φ` (at valuation `v₀`). -/
def SoundEnforcer (φ : MF B D) (v₀ : ℕ → D) (E : InputTrace B D → Tr B ℕ D) : Prop :=
  ∀ ρ i, φ.sat (E ρ) [] i v₀

/-- **End-to-end correctness of Enfflash** (paper: *Compilation
    correctness*).  If the compiler produces a program `P` for the policy
    `□φ` and its static checks succeed, then the enforcer running `P` is a
    sound enforcer of `□φ`: on every valid input trace, the output of the
    enforcement loop satisfies `□φ`. -/
theorem enforcement_correct {Φ : Policy B D} (P : Compiled Φ) (h : P.Checks) :
    SoundEnforcer Φ.φ P.v₀ (enforce P h) := by
  intro ρ
  have hQ := h.wf ρ
  have hord := lnf_ordered Φ.φ Φ.wf
  have hlets := norm_presentOps Φ.φ Φ.past [] [] (by intro p d h; simp at h)
  have htab := tables_compute hQ hord hlets
  have hK : ∀ j, ∃ tab t, (loopRun hQ).K j = _ := fun j => pt_K hQ j
  have hχ := enforcer_sound_topo (wellFounded_lt) P.comp.valid P.comp.rewrite P.comp.choice
    (ldOf Φ.Γ) P.rules P.hasC P.hasR P.present P.order (loopRun hQ) (outTr_mono hQ) htab
    (fun j => by
      obtain ⟨tab, t, he⟩ := hK j; rw [he]
      exact fun W W' p hag => tables_letDeps Φ.Γ P.v₀ hord tab t W W' p hag)
    (fun j => by obtain ⟨tab, t, he⟩ := hK j; rw [he]; exact h.conflicts tab t)
  intro i
  exact ((norm_correct Φ.φ [] Φ.wf [] []).2.2 _ P.v₀ [] (letSem_of_tables _ P.v₀ htab)
    (by intro k ar h; simp at h) i P.v₀).1 (hχ i)

end Enfflash
